### ISSUE TITLE
Redesign comments component

### ISSUE THREAD

**Issue by MangopearUK** [MangopearUK/mangopear-theme#14]
There's a lot of gumph surround the comments section of the website - a streamlined UI is much needed.

This is also a good opportunity to:
- make comments look more modern
- ensure social media login for easier commenting
- reduce spam comments through invisible Captcha
- enforce a code of conduct
- encourage conversation

## Current comments UI

![image](https://user-images.githubusercontent.com/3357509/39665484-2292158c-508d-11e8-89eb-87146c91a3a3.png)

## Tasks to complete as part of redesign

- [x] Move comments file from root of theme to `template-partials`
- [x] Rename section title to "Comments"
- [x] Redesign entire component
- [ ] Allow users to be emailed (or notified?) when someone replies to them
- [x] Enable social login
- [x] Enable invisible Captcha
- [ ] Add a code of conduct for suitable, friendly commenting
- [x] Add documentation to file

**Comment by MangopearUK** [comment]
Done and deployed.
